(function(){
'use strict';
const CFG=window.EPP_CUSTOMER_CONFIG||window.EVENT_PLANNER_CUSTOMER||{};
const DB=(CFG.firebaseConfig&&CFG.firebaseConfig.databaseURL||'').replace(/\/$/,'');
const CUSTOMER=CFG.customerId||'amsterdam-verhuur';
const APP_PATH=CFG.appStatePath||('customers/'+CUSTOMER+'/appState');
const LIC_PATH=CFG.licensePath||('customers/'+CUSTOMER+'/license');
let state={users:[],orders:[],materials:[],alerts:[],driverMessages:[]};
let user=null;
const $=id=>document.getElementById(id);
function esc(v){return String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));}
function clean(v){return String(v||'').trim();}
function lower(v){return clean(v).toLowerCase();}
function toast(t){const e=$('toast'); if(!e){alert(t);return;} e.textContent=t; e.classList.add('show'); clearTimeout(e._t); e._t=setTimeout(()=>e.classList.remove('show'),3000);}
function status(t){const e=$('status'); if(e)e.textContent=t;}
function dbUrl(path){return DB+'/'+path.split('/').map(encodeURIComponent).join('/')+'.json?cb='+Date.now();}
async function getJson(path){const r=await fetch(dbUrl(path),{cache:'no-store'}); if(!r.ok)throw new Error('HTTP '+r.status); return await r.json();}
async function putJson(path,data){const r=await fetch(DB+'/'+path.split('/').map(encodeURIComponent).join('/')+'.json',{method:'PUT',headers:{'content-type':'application/json'},body:JSON.stringify(data)}); if(!r.ok)throw new Error('HTTP '+r.status); return await r.json();}
function dateOnly(d){return new Date(d.getFullYear(),d.getMonth(),d.getDate()).getTime();}
function parseDate(v){v=clean(v); if(!v)return null; let m=v.match(/^(\d{4})-(\d{1,2})-(\d{1,2})$/); if(m)return new Date(+m[1],+m[2]-1,+m[3]); m=v.match(/^(\d{1,2})-(\d{1,2})-(\d{4})$/); if(m)return new Date(+m[3],+m[2]-1,+m[1]); const d=new Date(v); return isNaN(d)?null:d;}
function showBlock(title,msg){let el=document.getElementById('licenseBlock'); if(!el){el=document.createElement('div');el.id='licenseBlock';el.className='license-block';document.body.appendChild(el);} el.innerHTML='<div class="box"><h2>'+esc(title)+'</h2><p>'+esc(msg)+'</p></div>';}
function removeBlock(){const el=document.getElementById('licenseBlock'); if(el)el.remove();}
async function checkLicense(){ if(location.protocol==='file:')return true; if(!DB){showBlock('Config ontbreekt','Firebase databaseURL ontbreekt.');return false;} const lic=await getJson(LIC_PATH).catch(()=>null); if(!lic||typeof lic!=='object'){showBlock('Licentie geblokkeerd','Licentie niet gevonden.');return false;} if(lic.active===false||lic.blocked===true||String(lic.status||'').toLowerCase()==='blocked'||lic.paid===false){showBlock('Licentie geblokkeerd','Deze app is geblokkeerd door de licentie.');return false;} const until=parseDate(lic.validUntil||lic.paidUntil||''); if(until&&dateOnly(until)<dateOnly(new Date())){showBlock('Licentie verlopen','Licentie is verlopen op '+clean(lic.validUntil||lic.paidUntil)+'.');return false;} removeBlock(); return true; }
function normalize(){ state=state&&typeof state==='object'?state:{}; ['users','orders','materials','alerts','driverMessages'].forEach(k=>{if(!Array.isArray(state[k]))state[k]=[];}); state.users=state.users.filter(u=>String(u&&u.pin)!=='1111'); if(!state.users.some(u=>String(u.pin)==='3330')) state.users.push({id:'ams_admin_3330',name:'Admin',pin:'3330',role:'Admin',active:true,rights:{resolve:true,gps:true,agenda:true,prices:true}}); }
async function load(){status('Data laden...'); const s=await getJson(APP_PATH); state=s||{}; normalize(); status('Data geladen');}
async function save(){state.updatedAt=new Date().toISOString(); await putJson(APP_PATH,state);}
function orderStart(o){return clean(o.start||o.dateStart||o.startDate||o.date||'');}
function orderEnd(o){return clean(o.end||o.dateEnd||o.endDate||orderStart(o));}
function niceDate(v){v=clean(v).slice(0,10); const p=v.split('-'); return p.length===3?p[2]+'-'+p[1]+'-'+p[0]:v;}
function customer(o){return clean(o.customerName||(o.customer&&o.customer.name)||o.klant||'');}
function address(o){const p=[]; const add=v=>{v=clean(v); if(v&&!p.includes(v))p.push(v);}; [o.locationName,o.locationAddress,o.locationStreet,o.locationZip,o.locationCity,o.address,o.street,o.zip,o.city].forEach(add); if(o.location&&typeof o.location==='object')[o.location.name,o.location.address,o.location.street,o.location.zip,o.location.city].forEach(add); return p.join(', ');}
function mats(o){const m=o.materials||o.mats||[]; return Array.isArray(m)?m.map(x=>typeof x==='string'?x:(x.code||x.name||x.title||'')).filter(Boolean).join(', '):'';}
function isBad(o){const s=lower(o.status); return /geann|annul|cancel|verwijderd/.test(s);}
function driverUsers(){return (state.users||[]).filter(u=>u&&u.active!==false&&/bezorger|driver/i.test(u.role||''));}
function orders(){const q=lower($('searchBox')&&$('searchBox').value); return (state.orders||[]).filter(o=>!isBad(o)).filter(o=>{const hay=lower([o.number,o.title,customer(o),address(o),mats(o),o.driverName,o.driver,o.bezorger,o.status].join(' ')); return !q||hay.includes(q);}).sort((a,b)=>orderStart(a).localeCompare(orderStart(b)));}
function renderOrders(){const box=$('orders'); const rows=orders(); if(!rows.length){box.innerHTML='<div class="empty">Geen opdrachten gevonden.</div>';return;} const ds=driverUsers(); box.innerHTML=rows.map(o=>{const cur=clean(o.driverName||o.driver||o.bezorger||''); const sel='<select onchange="BNSPlanner.assign(\''+esc(o.id)+'\',this.value)"><option value="">Geen bezorger</option>'+ds.map(d=>'<option '+(clean(d.name)===cur?'selected':'')+' value="'+esc(d.name)+'">'+esc(d.name)+'</option>').join('')+'</select>'; return '<article class="order-card"><span class="order-number">'+esc(o.number||o.id||'')+'</span><div class="order-title">'+esc(o.title||customer(o)||'Opdracht')+'</div><div class="badges"><span class="badge">'+esc(niceDate(orderStart(o)))+'</span><span class="badge warn">t/m '+esc(niceDate(orderEnd(o)))+'</span><span class="badge dark">'+esc(o.status||'')+'</span></div><div class="meta"><div><b>Klant:</b> '+esc(customer(o)||'-')+'</div><div><b>Adres:</b> '+esc(address(o)||'-')+'</div><div><b>Materiaal:</b> '+esc(mats(o)||'-')+'</div><label>Bezorger '+sel+'</label></div></article>';}).join('');}
function renderAlerts(){const box=$('alerts'); const rows=[...(state.driverMessages||[]),...(state.alerts||[]).filter(a=>String(a.type||'')==='driver')].filter(a=>!a.resolved).sort((a,b)=>String(b.createdAt||'').localeCompare(String(a.createdAt||''))); const seen={}; const unique=rows.filter(a=>{const id=a.id||a.createdAt||JSON.stringify(a); if(seen[id])return false; seen[id]=1; return true;}); if(!unique.length){box.innerHTML='<div class="empty">Geen open meldingen.</div>';return;} box.innerHTML=unique.map(a=>'<article class="order-card"><div class="order-title">'+esc(a.type||a.title||'Melding')+'</div><div class="meta"><div><b>Opdracht:</b> '+esc(a.orderNumber||a.orderId||'')+' '+esc(a.orderTitle||'')+'</div><div><b>Bezorger:</b> '+esc(a.driverName||'')+'</div><div><b>Tekst:</b> '+esc(a.message||a.text||'')+'</div><div><b>Tijd:</b> '+esc(a.createdAt||'')+'</div></div><button class="btn-green" onclick="BNSPlanner.resolve(\''+esc(a.id)+'\')">Afmelden</button></article>').join('');}
function render(){renderOrders();renderAlerts();}
function populate(){const users=(state.users||[]).filter(u=>u&&u.active!==false&&String(u.pin)!=='1111'&&/planner|admin/i.test(u.role||'')); $('loginName').innerHTML=users.map(u=>'<option value="'+esc(u.id)+'">'+esc(u.name||u.id)+' ('+esc(u.role||'')+')</option>').join('')||'<option value="">Geen planner/admin</option>';}
function login(){const id=$('loginName').value; const pin=clean($('loginPin').value); const u=(state.users||[]).find(x=>String(x.id)===String(id)); if(!u||String(u.pin)!==pin||String(pin)==='1111'){toast('PIN niet goed');return;} user=u; $('loginBox').classList.add('hidden'); $('appBox').classList.remove('hidden'); $('logoutBtn').classList.remove('hidden'); $('who').textContent=u.name+' - '+(u.role||''); render();}
function orderById(id){return (state.orders||[]).find(o=>String(o.id)===String(id));}
window.BNSPlanner={assign:async function(id,name){const o=orderById(id); if(!o)return; o.driverName=name; o.driver=name; o.updatedAt=new Date().toISOString(); await save(); toast(name?'Bezorger gekoppeld':'Bezorger leeg gemaakt'); render();},resolve:async function(id){(state.driverMessages||[]).forEach(a=>{if(String(a.id)===String(id))a.resolved=true;}); (state.alerts||[]).forEach(a=>{if(String(a.id)===String(id))a.resolved=true;}); await save(); toast('Melding afgemeld'); render();}};
async function start(){try{await checkLicense(); await load(); populate(); $('loginBtn').onclick=login; $('refreshBtn').onclick=async()=>{await load();render();toast('Verversd')}; $('clearSearchBtn').onclick=()=>{$('searchBox').value='';render()}; $('searchBox').oninput=renderOrders; $('logoutBtn').onclick=()=>location.reload(); status('Klaar');}catch(e){status('Fout: '+e.message); toast('Fout bij laden');}}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',start);else start();
})();
