(function(){
'use strict';
const CFG=window.EPP_CUSTOMER_CONFIG||window.EVENT_PLANNER_CUSTOMER||{};
const DB=(CFG.firebaseConfig&&CFG.firebaseConfig.databaseURL||'').replace(/\/$/,'');
const CUSTOMER=CFG.customerId||'amsterdam-verhuur';
const APP_PATH=CFG.appStatePath||('customers/'+CUSTOMER+'/appState');
const LIC_PATH=CFG.licensePath||('customers/'+CUSTOMER+'/license');
const MASTER=String(CFG.masterPin||'9119');
let state={users:[],orders:[],materials:[],alerts:[],driverMessages:[]};
let user=null;
const $=id=>document.getElementById(id);
function esc(v){return String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));}
function clean(v){return String(v||'').trim();}
function lower(v){return clean(v).toLowerCase();}
function toast(t){const e=$('toast'); if(!e){alert(t);return;} e.textContent=t; e.classList.add('show'); clearTimeout(e._t); e._t=setTimeout(()=>e.classList.remove('show'),3000);}
function status(t){const e=$('status'); if(e)e.textContent=t;}
function dbUrl(path){return DB+'/'+path.split('/').map(encodeURIComponent).join('/')+'.json?cb='+Date.now();}
async function getJson(path){const r=await fetch(dbUrl(path),{cache:'no-store'}); if(!r.ok)throw new Error('HTTP '+r.status); return await r.json();}
async function putJson(path,data){const r=await fetch(DB+'/'+path.split('/').map(encodeURIComponent).join('/')+'.json',{method:'PUT',headers:{'content-type':'application/json'},body:JSON.stringify(data)}); if(!r.ok)throw new Error('HTTP '+r.status); return await r.json();}
function dateOnly(d){return new Date(d.getFullYear(),d.getMonth(),d.getDate()).getTime();}
function parseDate(v){v=clean(v); if(!v)return null; let m=v.match(/^(\d{4})-(\d{1,2})-(\d{1,2})$/); if(m)return new Date(+m[1],+m[2]-1,+m[3]); m=v.match(/^(\d{1,2})-(\d{1,2})-(\d{4})$/); if(m)return new Date(+m[3],+m[2]-1,+m[1]); const d=new Date(v); return isNaN(d)?null:d;}
function showBlock(title,msg){let el=document.getElementById('licenseBlock'); if(!el){el=document.createElement('div');el.id='licenseBlock';el.className='license-block';document.body.appendChild(el);} el.innerHTML='<div class="box"><h2>'+esc(title)+'</h2><p>'+esc(msg)+'</p></div>';}
function removeBlock(){const el=document.getElementById('licenseBlock'); if(el)el.remove();}
async function checkLicense(){ if(location.protocol==='file:')return true; if(!DB){showBlock('Config ontbreekt','Firebase databaseURL ontbreekt.');return false;} const lic=await getJson(LIC_PATH).catch(()=>null); if(!lic||typeof lic!=='object'){showBlock('Licentie geblokkeerd','Licentie niet gevonden.');return false;} if(lic.active===false||lic.blocked===true||String(lic.status||'').toLowerCase()==='blocked'||lic.paid===false){showBlock('Licentie geblokkeerd','Deze app is geblokkeerd door de licentie.');return false;} const until=parseDate(lic.validUntil||lic.paidUntil||''); if(until&&dateOnly(until)<dateOnly(new Date())){showBlock('Licentie verlopen','Licentie is verlopen op '+clean(lic.validUntil||lic.paidUntil)+'.');return false;} removeBlock(); return true; }
function normalize(){ state=state&&typeof state==='object'?state:{}; ['users','orders','materials','alerts','driverMessages'].forEach(k=>{if(!Array.isArray(state[k]))state[k]=[];}); state.users=state.users.filter(u=>String(u&&u.pin)!=='1111'); if(!state.users.some(u=>String(u.pin)==='3330')) state.users.push({id:'ams_admin_3330',name:'Admin',pin:'3330',role:'Admin',active:true,rights:{resolve:true,gps:true,agenda:true,prices:true}}); }
async function load(){status('Data laden...'); const s=await getJson(APP_PATH); state=s||{}; normalize(); status('Data geladen');}
async function save(){state.updatedAt=new Date().toISOString(); await putJson(APP_PATH,state);}
function orderStart(o){return clean(o.start||o.dateStart||o.startDate||o.date||'');}
function orderEnd(o){return clean(o.end||o.dateEnd||o.endDate||orderStart(o));}
function niceDate(v){v=clean(v).slice(0,10); const p=v.split('-'); return p.length===3?p[2]+'-'+p[1]+'-'+p[0]:v;}
function customer(o){return clean(o.customerName||(o.customer&&o.customer.name)||o.klant||'');}
function address(o){const p=[]; const add=v=>{v=clean(v); if(v&&!p.includes(v))p.push(v);}; [o.locationName,o.locationAddress,o.locationStreet,o.locationZip,o.locationCity,o.address,o.street,o.zip,o.city].forEach(add); if(o.location&&typeof o.location==='object')[o.location.name,o.location.address,o.location.street,o.location.zip,o.location.city].forEach(add); return p.join(', ');}
function mats(o){const m=o.materials||o.mats||[]; return Array.isArray(m)?m.map(x=>typeof x==='string'?x:(x.code||x.name||x.title||'')).filter(Boolean).join(', '):'';}
function isBad(o){const s=lower(o.status); return /geann|annul|cancel|uitgevoerd|afgerond|done|klaar|verwijderd/.test(s);}
function visibleOrders(){const q=lower($('searchBox')&&$('searchBox').value); return (state.orders||[]).filter(o=>!isBad(o)).filter(o=>{const role=lower(user&&user.role); const nm=lower(user&&user.name); const assigned=lower(o.driverName||o.driver||o.bezorger||''); if(role==='bezorger'&&assigned&&assigned!==nm)return false; const hay=lower([o.number,o.title,customer(o),address(o),mats(o),assigned,o.status].join(' ')); return !q||hay.includes(q);}).sort((a,b)=>orderStart(a).localeCompare(orderStart(b)));}
function renderOrders(){const box=$('orders'); const rows=visibleOrders(); if(!rows.length){box.innerHTML='<div class="empty">Geen opdrachten gevonden.</div>';return;} box.innerHTML=rows.map(o=>'<article class="order-card"><span class="order-number">'+esc(o.number||o.id||'')+'</span><div class="order-title">'+esc(o.title||customer(o)||'Opdracht')+'</div><div class="badges"><span class="badge">'+esc(niceDate(orderStart(o)))+'</span><span class="badge warn">t/m '+esc(niceDate(orderEnd(o)))+'</span><span class="badge dark">'+esc(o.status||'')+'</span></div><div class="meta"><div><b>Klant:</b> '+esc(customer(o)||'-')+'</div><div><b>Adres:</b> '+esc(address(o)||'-')+'</div><div><b>Materiaal:</b> '+esc(mats(o)||'-')+'</div></div><div class="action-grid"><button onclick="BNSDriver.open(\''+esc(o.id)+'\')">Open</button><button class="btn-green" onclick="BNSDriver.msg(\''+esc(o.id)+'\',\'geleverd\')">Geleverd</button><button class="btn-orange" onclick="BNSDriver.msg(\''+esc(o.id)+'\',\'ophalen gereed\')">Ophalen gereed</button><button class="btn-red" onclick="BNSDriver.msg(\''+esc(o.id)+'\',\'schade\')">Schade</button></div></article>').join('');}
function login(){const id=$('loginName').value; const pin=clean($('loginPin').value); const u=(state.users||[]).find(x=>String(x.id)===String(id)); if(!u||String(u.pin)!==pin||String(pin)==='1111'){toast('PIN niet goed');return;} user=u; sessionStorage.setItem('epp_driver_user',JSON.stringify({id:u.id,pin:u.pin})); $('loginBox').classList.add('hidden'); $('appBox').classList.remove('hidden'); $('logoutBtn').classList.remove('hidden'); $('who').textContent=u.name+' - '+(u.role||''); renderOrders();}
function populate(){const users=(state.users||[]).filter(u=>u&&u.active!==false&&String(u.pin)!=='1111'&&(/bezorger|planner|admin/i.test(u.role||''))); $('loginName').innerHTML=users.map(u=>'<option value="'+esc(u.id)+'">'+esc(u.name||u.id)+' ('+esc(u.role||'')+')</option>').join('')||'<option value="">Geen gebruikers</option>';}
function orderById(id){return (state.orders||[]).find(o=>String(o.id)===String(id));}
window.BNSDriver={open:function(id){const o=orderById(id); if(!o)return; $('ordersView').classList.add('hidden'); const d=$('detailView'); d.classList.remove('hidden'); d.innerHTML='<div class="detail-card"><button class="btn-dark" onclick="BNSDriver.back()">Terug</button><h2>'+esc(o.title||customer(o)||'Opdracht')+'</h2><div class="meta"><div><b>Nummer:</b> '+esc(o.number||o.id||'')+'</div><div><b>Datum:</b> '+esc(niceDate(orderStart(o)))+' t/m '+esc(niceDate(orderEnd(o)))+'</div><div><b>Klant:</b> '+esc(customer(o)||'-')+'</div><div><b>Adres:</b> '+esc(address(o)||'-')+'</div><div><b>Materiaal:</b> '+esc(mats(o)||'-')+'</div><div><b>Extra:</b><br>'+esc(o.extra||'').replace(/\n/g,'<br>')+'</div></div><textarea id="driverNote" placeholder="Opmerking / schade / bijzonderheden"></textarea><div class="action-grid"><button class="btn-green" onclick="BNSDriver.msg(\''+esc(o.id)+'\',\'geleverd\')">Geleverd</button><button class="btn-orange" onclick="BNSDriver.msg(\''+esc(o.id)+'\',\'ophalen gereed\')">Ophalen gereed</button><button class="btn-purple" onclick="BNSDriver.msg(\''+esc(o.id)+'\',\'opmerking\')">Opmerking</button><button class="btn-red" onclick="BNSDriver.msg(\''+esc(o.id)+'\',\'schade\')">Schade</button></div></div>';},back:function(){$('detailView').classList.add('hidden');$('ordersView').classList.remove('hidden');},msg:async function(id,type){const o=orderById(id); if(!o)return; const note=clean($('driverNote')&&$('driverNote').value); const msg={id:'dm_'+Date.now()+'_'+Math.random().toString(36).slice(2,7),type:type,orderId:o.id,orderNumber:o.number||'',orderTitle:o.title||'',driverName:user?user.name:'',message:note,createdAt:new Date().toISOString(),resolved:false,source:'driver'}; state.driverMessages.push(msg); state.alerts.push({id:msg.id,title:'Bezorger: '+type,text:(o.number||'')+' '+(o.title||'')+(note?' - '+note:''),type:'driver',createdAt:msg.createdAt,resolved:false,orderId:o.id}); await save(); toast('Melding verstuurd'); renderOrders();}};
async function start(){try{await checkLicense(); await load(); populate(); $('loginBtn').onclick=login; $('refreshBtn').onclick=async()=>{await load();renderOrders();toast('Verversd')}; $('clearSearchBtn').onclick=()=>{$('searchBox').value='';renderOrders()}; $('searchBox').oninput=renderOrders; $('logoutBtn').onclick=()=>{sessionStorage.removeItem('epp_driver_user');location.reload()}; status('Klaar');}catch(e){status('Fout: '+e.message); toast('Fout bij laden');}}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',start);else start();
})();
